#pragma once

enum DIRECTION { DIR_LEFT, DIR_TOP, DIR_RIGHT, DIR_BOTTOM, DIR_END };
enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_ITEM, OBJ_EFFECT, OBJ_OBSTACLE, OBJ_END }; //OBJ_ITEM
enum UIID {UI_FRONT, UI_BACK, UI_END };
enum ITEMTYPE {ITEM_LIFE, ITEM_SUPER, ITEM_SCORE, ITEM_CLOCK, ITEM_WEAPON, ITEM_END};
enum BULLET_TYPE { PLAYER_BULLET, MONSTER_BULLET, BULLET_END };
enum MONSTERTYPE { MONSTER_A, MONSTER_B, MONSTER_C, MONSTER_BOSS, MONSTER_END };
