#pragma once

enum DIRECTION { DIR_LEFT, DIR_TOP, DIR_RIGHT, DIR_BOTTOM, DIR_END };
enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_ITEM, OBJ_EFFECT, OBJ_END }; //OBJ_ITEM
enum UIID {UI_FRONT, UI_BACK, UI_END };
enum ITEMID {ITEM_POWER, ITEM_SHIELD, ITEM_BOMB, ITEM_END};
enum ASSISTANT_DIR { AST_LEFT, AST_RIGHT, AST_END};
enum BULLET_TYPE { PLAYER_BULLET, MONSTER_BULLET, BULLET_END };
