#pragma once

enum DIRECTION { DIR_LEFT, DIR_TOP, DIR_RIGHT, DIR_BOTTOM, DIR_END };
enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_ITEM, OBJ_WALL, OBJ_OBSTACLE, OBJ_EFFECT, OBJ_END };
enum UIID {UI_FRONT, UI_BACK, UI_END };
enum BULLET_TYPE { PLAYER_BULLET, MONSTER_BULLET, BULLET_END };
enum MONSTERTYPE { MONSTER_A, MONSTER_B, MONSTER_C, MONSTER_BOSS, MONSTER_END };
